### ISSUE TITLE
有无详细点的安装教程呢

### ISSUE THREAD

**Issue by Arturia169** [TrymenT-AlphA/arkbot#3]

**Comment by TrymenT-AlphA** [comment]
先配置好env，env.dev，env.prod三个文件，然后用pipenv install创建python的虚拟环境，然后pipenv run python bot.py，之后应该有个引导之类的，有点久远，不确定能不能跑得动（bushi）

**Comment by adslk** [comment]
请问下这个项目还有在更新吗，能否优化一下readme，给个详细一点的安装配置流程？

**Comment by TrymenT-AlphA** [comment]
@adslk 该版本已废弃，1.6之后将恢复更新
